config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: %i[new create destroy]
  resources :users, only: %i[new create index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string
#  name            :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: /\A[\w+\-.]+@[\w\-.]+\.[a-z]+\z/i},
                    uniqueness: true
  before_validation {email.downcase!}

  has_secure_password
  validates :password, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: %i[new create]
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました!"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path, notice: "ログアウトしました!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[new create]
  before_action :set_user, only: %i[show]
  def index
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: "登録しました!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__logo"><a href="#">Home</a></div>
      <button class="hamberger" type="button" id="hamberger" data-target="#gnav">
        <span class="hamberger__inner">
          <span class="hamberger__line"></span>
          <span class="hamberger__txt">MENU</span>
        </span>
      </button>
      <nav class="gnav" id="gnav">
        <ul class="gnav__list">
          <% if logged_in? %>
            <li class="gnav__item"><%= link_to "Profile", user_path(current_user.id), class: "gnav__link" %></li>
            <li class="gnav__item"><%= link_to "Logout", session_path(current_user.id), method: :delete, class: "gnav__link" %></li>
          <% else %>
            <li class="gnav__item"><%= link_to "Signup", new_user_path, class: "gnav__link" %></li>
            <li class="gnav__item"><%= link_to "Login", new_session_path, class: "gnav__link" %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: ["alert", "alert-#{key}"]) %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>
<div class="form-wrapper">
  <% if @user.errors.any? %>
    <div id="error_explanation" >
      <div class="alert alert-danger">
        <h2><%= pluralize(@user.errors.count,"error") %> prohibited this <%= @user.name %> from being saved:</h2>
        <ul>
          <%= @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <%= form_with(model: @user, local: true, class: "form" ) do |f| %>
    <div class="form__item">
      <%= f.label :name, "名前", class: "form__ttl" %>
      <div class="form__body">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="form__item">
      <%= f.label :email, "Email", class: "form__ttl" %>
      <div class="form__body">
        <%= f.email_field :email %>
      </div>
    </div>
    <div class="form__item">
      <%= f.label :password, "パスワード", class: "form__ttl" %>
      <div class="form__body">
        <%= f.password_field :password, placeholder: "6文字以上", minlength: 6 %>
      </div>
    </div>
    <div class="form__item">
      <%= f.label :password_confirmation, "パスワード確認用", class: "form__ttl" %>
      <div class="form__body">
        <%= f.password_field :password_confirmation, placeholder: "再度同じものを入力" %>
      </div>
    </div>
    <%= f.submit "登　録", class: "btn btn-color" %>
  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, "your page") %>
<h1><%= @user.name %>さんのページ</h1>
<div class="user-profile-wrapper">
  <div class="user">
    <div class="user__item">
      <div class="user__ttl">名前</div>
      <div class="user__name"><%= @user.name %></div>
    </div>
    <div class="user__item">
      <div class="user__ttl">メールアドレス</div>
      <div class="user__email"><%= @user.email %></div>
    </div>
  </div>

</div>